# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window_base.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(200, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(200, 400))
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainWindow)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layoutToolBox = QtWidgets.QHBoxLayout()
        self.layoutToolBox.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layoutToolBox.setContentsMargins(-1, -1, 0, -1)
        self.layoutToolBox.setSpacing(0)
        self.layoutToolBox.setObjectName("layoutToolBox")
        self.toolBox_2 = QtWidgets.QToolBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_2.sizePolicy().hasHeightForWidth())
        self.toolBox_2.setSizePolicy(sizePolicy)
        self.toolBox_2.setMinimumSize(QtCore.QSize(10, 10))
        self.toolBox_2.setMaximumSize(QtCore.QSize(160, 16777215))
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 160, 290))
        self.page_4.setObjectName("page_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 160, 116))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_6.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_6.addWidget(self.pushButton_6)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.toolBox_2.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 160, 290))
        self.page_5.setObjectName("page_5")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.page_5)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 160, 80))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_4.addWidget(self.pushButton_8)
        self.toolBox_2.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 160, 290))
        self.page_6.setObjectName("page_6")
        self.toolBox_2.addItem(self.page_6, "")
        self.layoutToolBox.addWidget(self.toolBox_2)
        self.horizontalLayout.addLayout(self.layoutToolBox)
        self.layoutFormSocio = QtWidgets.QVBoxLayout()
        self.layoutFormSocio.setObjectName("layoutFormSocio")
        self.horizontalLayout.addLayout(self.layoutFormSocio)

        self.retranslateUi(MainWindow)
        self.toolBox_2.setCurrentIndex(0)
        self.pushButton_5.clicked.connect(MainWindow.onClickedAltaSocio)
        self.pushButton_6.clicked.connect(MainWindow.onClickedConsultaSocio)
        self.pushButton.clicked.connect(MainWindow.onClickedConsultaAlumno)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menú"))
        self.pushButton_5.setText(_translate("MainWindow", "Insertar"))
        self.pushButton_6.setText(_translate("MainWindow", "Consultar Socio"))
        self.pushButton.setText(_translate("MainWindow", "Consultar Alumno"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_4), _translate("MainWindow", "Socios"))
        self.pushButton_7.setText(_translate("MainWindow", "Registrar"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_5), _translate("MainWindow", "Cuotas"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_6), _translate("MainWindow", "Reportes"))
