# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/form_socio.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormSocio(object):
    def setupUi(self, FormSocio):
        FormSocio.setObjectName("FormSocio")
        FormSocio.resize(464, 348)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(FormSocio)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(FormSocio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.lineEditDNISocio = QtWidgets.QLineEdit(FormSocio)
        self.lineEditDNISocio.setObjectName("lineEditDNISocio")
        self.verticalLayout.addWidget(self.lineEditDNISocio)
        self.lineEditApellidoSocio = QtWidgets.QLineEdit(FormSocio)
        self.lineEditApellidoSocio.setText("")
        self.lineEditApellidoSocio.setObjectName("lineEditApellidoSocio")
        self.verticalLayout.addWidget(self.lineEditApellidoSocio)
        self.lineEditNombreSocio = QtWidgets.QLineEdit(FormSocio)
        self.lineEditNombreSocio.setObjectName("lineEditNombreSocio")
        self.verticalLayout.addWidget(self.lineEditNombreSocio)
        self.lineEditDomicilioSocio = QtWidgets.QLineEdit(FormSocio)
        self.lineEditDomicilioSocio.setObjectName("lineEditDomicilioSocio")
        self.verticalLayout.addWidget(self.lineEditDomicilioSocio)
        self.lineEditTelSocio = QtWidgets.QLineEdit(FormSocio)
        self.lineEditTelSocio.setObjectName("lineEditTelSocio")
        self.verticalLayout.addWidget(self.lineEditTelSocio)
        self.botonAgregarOtroAlumno = QtWidgets.QPushButton(FormSocio)
        self.botonAgregarOtroAlumno.setObjectName("botonAgregarOtroAlumno")
        self.verticalLayout.addWidget(self.botonAgregarOtroAlumno)
        self.botonSalir = QtWidgets.QPushButton(FormSocio)
        self.botonSalir.setObjectName("botonSalir")
        self.verticalLayout.addWidget(self.botonSalir)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(FormSocio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.lineEditDNIAlumno = QtWidgets.QLineEdit(FormSocio)
        self.lineEditDNIAlumno.setObjectName("lineEditDNIAlumno")
        self.verticalLayout_2.addWidget(self.lineEditDNIAlumno)
        self.lineEditApellidoAlumno = QtWidgets.QLineEdit(FormSocio)
        self.lineEditApellidoAlumno.setText("")
        self.lineEditApellidoAlumno.setObjectName("lineEditApellidoAlumno")
        self.verticalLayout_2.addWidget(self.lineEditApellidoAlumno)
        self.lineEditNombreAlumno = QtWidgets.QLineEdit(FormSocio)
        self.lineEditNombreAlumno.setObjectName("lineEditNombreAlumno")
        self.verticalLayout_2.addWidget(self.lineEditNombreAlumno)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelGrado = QtWidgets.QLabel(FormSocio)
        self.labelGrado.setObjectName("labelGrado")
        self.horizontalLayout_2.addWidget(self.labelGrado)
        self.comboBoxGrado = QtWidgets.QComboBox(FormSocio)
        self.comboBoxGrado.setObjectName("comboBoxGrado")
        self.horizontalLayout_2.addWidget(self.comboBoxGrado)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelDivision = QtWidgets.QLabel(FormSocio)
        self.labelDivision.setObjectName("labelDivision")
        self.horizontalLayout.addWidget(self.labelDivision)
        self.comboBoxDivision = QtWidgets.QComboBox(FormSocio)
        self.comboBoxDivision.setObjectName("comboBoxDivision")
        self.horizontalLayout.addWidget(self.comboBoxDivision)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelTurno = QtWidgets.QLabel(FormSocio)
        self.labelTurno.setObjectName("labelTurno")
        self.horizontalLayout_5.addWidget(self.labelTurno)
        self.comboBoxTurno = QtWidgets.QComboBox(FormSocio)
        self.comboBoxTurno.setObjectName("comboBoxTurno")
        self.horizontalLayout_5.addWidget(self.comboBoxTurno)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.saveSocio = QtWidgets.QPushButton(FormSocio)
        self.saveSocio.setObjectName("saveSocio")
        self.verticalLayout_2.addWidget(self.saveSocio)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox = QtWidgets.QCheckBox(FormSocio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_6.addWidget(self.checkBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.labelMsjSocio = QtWidgets.QLabel(FormSocio)
        self.labelMsjSocio.setEnabled(True)
        self.labelMsjSocio.setText("")
        self.labelMsjSocio.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelMsjSocio.setObjectName("labelMsjSocio")
        self.horizontalLayout_4.addWidget(self.labelMsjSocio)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)

        self.retranslateUi(FormSocio)
        self.botonSalir.clicked.connect(FormSocio.clickedExitFormSocio)
        self.saveSocio.clicked.connect(FormSocio.clickedSaveSocio)
        QtCore.QMetaObject.connectSlotsByName(FormSocio)

    def retranslateUi(self, FormSocio):
        _translate = QtCore.QCoreApplication.translate
        FormSocio.setWindowTitle(_translate("FormSocio", "Formulario Socio"))
        self.label.setText(_translate("FormSocio", "Socio"))
        self.lineEditDNISocio.setPlaceholderText(_translate("FormSocio", "D.N.I"))
        self.lineEditApellidoSocio.setPlaceholderText(_translate("FormSocio", "Apellido"))
        self.lineEditNombreSocio.setPlaceholderText(_translate("FormSocio", "Nombre"))
        self.lineEditDomicilioSocio.setPlaceholderText(_translate("FormSocio", "Domicilio"))
        self.lineEditTelSocio.setPlaceholderText(_translate("FormSocio", "Teléfono"))
        self.botonAgregarOtroAlumno.setText(_translate("FormSocio", "Insertar Otro Alumno"))
        self.botonSalir.setText(_translate("FormSocio", "Salir"))
        self.label_2.setText(_translate("FormSocio", "Alumno"))
        self.lineEditDNIAlumno.setPlaceholderText(_translate("FormSocio", "D.N.I"))
        self.lineEditApellidoAlumno.setPlaceholderText(_translate("FormSocio", "Apellido"))
        self.lineEditNombreAlumno.setPlaceholderText(_translate("FormSocio", "Nombre"))
        self.labelGrado.setText(_translate("FormSocio", "Grado"))
        self.labelDivision.setText(_translate("FormSocio", "División"))
        self.labelTurno.setText(_translate("FormSocio", "Turno"))
        self.saveSocio.setText(_translate("FormSocio", "Guardar"))
        self.checkBox.setText(_translate("FormSocio", "Modificar"))
